/*
 * Generated by Bluespec Compiler (build 2c1ed34)
 * 
 * On Mon Dec 14 18:02:57 IST 2020
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTestDRAM.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTestDRAM::MODEL_mkTestDRAM()
{
  mkTestDRAM_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTestDRAM()
{
  MODEL_mkTestDRAM *model = new MODEL_mkTestDRAM();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTestDRAM &INST_top = *((MOD_mkTestDRAM *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d898;
	 tUInt8 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d902;
	 tUInt8 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37___d838;
	 tUInt8 DEF_INST_top_DEF_NOT_start_wire_whas__39_40_OR_NOT_start_wire_w_ETC___d843;
	 tUInt8 DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860;
	 tUInt8 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d867;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read__63_EQ_11___d866;
	 tUInt8 DEF_INST_top_DEF_abort_wget____d837;
	 tUInt8 DEF_INST_top_DEF_abort_whas____d836;
	 tUInt8 DEF_INST_top_DEF_start_reg__h60659;
	 tUInt8 DEF_INST_top_DEF_running__h60745;
	 tUInt8 DEF_INST_top_DEF_start_wire_wget____d841;
	 tUInt8 DEF_INST_top_DEF_start_wire_whas____d839;
	 tUInt8 DEF_INST_top_DEF_start_reg_1__h54509;
	 tUInt8 DEF_INST_top_DEF_state_fired__h54511;
	 tUInt8 DEF_INST_top_DEF_state_mkFSMstate_read____d863;
	 DEF_INST_top_DEF_state_mkFSMstate_read____d863 = INST_top.INST_state_mkFSMstate.METH_read();
	 DEF_INST_top_DEF_abort_whas____d836 = INST_top.INST_abort.METH_whas();
	 DEF_INST_top_DEF_abort_wget____d837 = INST_top.INST_abort.METH_wget();
	 DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 = !DEF_INST_top_DEF_abort_whas____d836 || !DEF_INST_top_DEF_abort_wget____d837;
	 INST_top.DEF_CAN_FIRE_RL_action_l169c19 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_action_l169c19 = INST_top.DEF_CAN_FIRE_RL_action_l169c19;
	 INST_top.DEF_CAN_FIRE_RL_action_l170c19 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)2u;
	 INST_top.DEF_WILL_FIRE_RL_action_l170c19 = INST_top.DEF_CAN_FIRE_RL_action_l170c19;
	 INST_top.DEF_CAN_FIRE_RL_action_l171c13 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)3u;
	 INST_top.DEF_WILL_FIRE_RL_action_l171c13 = INST_top.DEF_CAN_FIRE_RL_action_l171c13;
	 INST_top.DEF_CAN_FIRE_RL_action_l172c13 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)4u;
	 INST_top.DEF_WILL_FIRE_RL_action_l172c13 = INST_top.DEF_CAN_FIRE_RL_action_l172c13;
	 INST_top.DEF_CAN_FIRE_RL_action_l178c19 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)5u;
	 INST_top.DEF_WILL_FIRE_RL_action_l178c19 = INST_top.DEF_CAN_FIRE_RL_action_l178c19;
	 INST_top.DEF_CAN_FIRE_RL_action_l179c19 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)6u;
	 INST_top.DEF_WILL_FIRE_RL_action_l179c19 = INST_top.DEF_CAN_FIRE_RL_action_l179c19;
	 INST_top.DEF_CAN_FIRE_RL_action_l181c13 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)8u;
	 INST_top.DEF_WILL_FIRE_RL_action_l181c13 = INST_top.DEF_CAN_FIRE_RL_action_l181c13;
	 INST_top.DEF_CAN_FIRE_RL_action_l180c19 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)7u;
	 INST_top.DEF_WILL_FIRE_RL_action_l180c19 = INST_top.DEF_CAN_FIRE_RL_action_l180c19;
	 INST_top.DEF_CAN_FIRE_RL_action_l182c13 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)9u;
	 INST_top.DEF_WILL_FIRE_RL_action_l182c13 = INST_top.DEF_CAN_FIRE_RL_action_l182c13;
	 INST_top.DEF_CAN_FIRE_RL_action_l188c13 = DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)10u;
	 INST_top.DEF_WILL_FIRE_RL_action_l188c13 = INST_top.DEF_CAN_FIRE_RL_action_l188c13;
	 DEF_INST_top_DEF_state_fired__h54511 = INST_top.INST_state_fired.METH_read();
	 DEF_INST_top_DEF_start_reg_1__h54509 = INST_top.INST_start_reg_1.METH_read();
	 DEF_INST_top_DEF_running__h60745 = INST_top.INST_running.METH_read();
	 DEF_INST_top_DEF_start_reg__h60659 = INST_top.INST_start_reg.METH_read();
	 DEF_INST_top_DEF_state_mkFSMstate_read__63_EQ_11___d866 = DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)11u;
	 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37___d838 = DEF_INST_top_DEF_abort_whas____d836 && DEF_INST_top_DEF_abort_wget____d837;
	 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d867 = (DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37___d838 || DEF_INST_top_DEF_state_mkFSMstate_read____d863 == (tUInt8)0u) || DEF_INST_top_DEF_state_mkFSMstate_read__63_EQ_11___d866;
	 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d898 = DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d867 && (!DEF_INST_top_DEF_start_reg_1__h54509 || DEF_INST_top_DEF_state_fired__h54511);
	 DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d902 = DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d898 && !DEF_INST_top_DEF_start_reg__h60659;
	 INST_top.DEF_CAN_FIRE_RL_auto_start = DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d902 && !DEF_INST_top_DEF_running__h60745;
	 INST_top.DEF_WILL_FIRE_RL_auto_start = INST_top.DEF_CAN_FIRE_RL_auto_start;
	 INST_top.DEF_CAN_FIRE_RL_auto_finish = DEF_INST_top_DEF_running__h60745 && DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d902;
	 INST_top.DEF_WILL_FIRE_RL_auto_finish = INST_top.DEF_CAN_FIRE_RL_auto_finish;
	 INST_top.DEF_CAN_FIRE_RL_fsm_start = DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d898 && DEF_INST_top_DEF_start_reg__h60659;
	 INST_top.DEF_WILL_FIRE_RL_fsm_start = INST_top.DEF_CAN_FIRE_RL_fsm_start;
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_2_master_rule = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_2_master_rule = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_2_master_rule;
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_0_master_rule = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_0_master_rule = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_0_master_rule && !(INST_top.DEF_WILL_FIRE_RL_action_l170c19);
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_1_master_rule = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_1_master_rule = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_1_master_rule && !(INST_top.DEF_WILL_FIRE_RL_action_l180c19);
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_3_master_rule = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_3_master_rule = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_csr_s_3_master_rule;
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule;
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule_1 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule_1 = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule_1;
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule_3 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule_3 = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule_3;
	 INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule_2 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule_2 = INST_top.DEF_CAN_FIRE_RL_my_ram_inst_port_i_rule_2;
	 INST_top.DEF_CAN_FIRE_RL_restart = (DEF_INST_top_DEF_start_reg_1__h54509 && !DEF_INST_top_DEF_state_fired__h54511) && DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860;
	 INST_top.DEF_WILL_FIRE_RL_restart = INST_top.DEF_CAN_FIRE_RL_restart;
	 INST_top.DEF_CAN_FIRE_RL_start_reg__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_start_reg__dreg_update = INST_top.DEF_CAN_FIRE_RL_start_reg__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_state_every = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_state_every = INST_top.DEF_CAN_FIRE_RL_state_every;
	 INST_top.DEF_CAN_FIRE___me_check_13 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_13 = INST_top.DEF_CAN_FIRE___me_check_13;
	 INST_top.DEF_CAN_FIRE_RL_state_fired__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_state_fired__dreg_update = INST_top.DEF_CAN_FIRE_RL_state_fired__dreg_update;
	 INST_top.DEF_CAN_FIRE___me_check_14 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_14 = INST_top.DEF_CAN_FIRE___me_check_14;
	 INST_top.DEF_CAN_FIRE___me_check_15 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_15 = INST_top.DEF_CAN_FIRE___me_check_15;
	 INST_top.DEF_CAN_FIRE___me_check_16 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_16 = INST_top.DEF_CAN_FIRE___me_check_16;
	 INST_top.DEF_CAN_FIRE___me_check_19 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_19 = INST_top.DEF_CAN_FIRE___me_check_19;
	 INST_top.DEF_CAN_FIRE___me_check_17 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_17 = INST_top.DEF_CAN_FIRE___me_check_17;
	 INST_top.DEF_CAN_FIRE___me_check_18 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_18 = INST_top.DEF_CAN_FIRE___me_check_18;
	 INST_top.DEF_CAN_FIRE___me_check_20 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_20 = INST_top.DEF_CAN_FIRE___me_check_20;
	 INST_top.DEF_CAN_FIRE___me_check_21 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_21 = INST_top.DEF_CAN_FIRE___me_check_21;
	 INST_top.DEF_CAN_FIRE___me_check_22 = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE___me_check_22 = INST_top.DEF_CAN_FIRE___me_check_22;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l170c19)
	   INST_top.RL_action_l170c19();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l180c19)
	   INST_top.RL_action_l180c19();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l171c13)
	   INST_top.RL_action_l171c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l172c13)
	   INST_top.RL_action_l172c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l181c13)
	   INST_top.RL_action_l181c13();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l188c13)
	   INST_top.RL_action_l188c13();
	 if (INST_top.DEF_WILL_FIRE_RL_auto_finish)
	   INST_top.RL_auto_finish();
	 if (INST_top.DEF_WILL_FIRE_RL_auto_start)
	   INST_top.RL_auto_start();
	 if (INST_top.DEF_WILL_FIRE_RL_fsm_start)
	   INST_top.RL_fsm_start();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_0_master_rule)
	   INST_top.RL_my_ram_inst_csr_s_0_master_rule();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_2_master_rule)
	   INST_top.RL_my_ram_inst_csr_s_2_master_rule();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_1_master_rule)
	   INST_top.RL_my_ram_inst_csr_s_1_master_rule();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_csr_s_3_master_rule)
	   INST_top.RL_my_ram_inst_csr_s_3_master_rule();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule)
	   INST_top.RL_my_ram_inst_port_i_rule();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l169c19)
	   INST_top.RL_action_l169c19();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule_1)
	   INST_top.RL_my_ram_inst_port_i_rule_1();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l178c19)
	   INST_top.RL_action_l178c19();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l179c19)
	   INST_top.RL_action_l179c19();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule_2)
	   INST_top.RL_my_ram_inst_port_i_rule_2();
	 if (INST_top.DEF_WILL_FIRE_RL_my_ram_inst_port_i_rule_3)
	   INST_top.RL_my_ram_inst_port_i_rule_3();
	 if (INST_top.DEF_WILL_FIRE_RL_action_l182c13)
	   INST_top.RL_action_l182c13();
	 if (INST_top.DEF_WILL_FIRE_RL_restart)
	   INST_top.RL_restart();
	 DEF_INST_top_DEF_start_wire_whas____d839 = INST_top.INST_start_wire.METH_whas();
	 DEF_INST_top_DEF_start_wire_wget____d841 = INST_top.INST_start_wire.METH_wget();
	 INST_top.DEF_CAN_FIRE_RL_action_l167c19 = ((DEF_INST_top_DEF_start_wire_whas____d839 && DEF_INST_top_DEF_start_wire_wget____d841) && DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37_38_OR_state__ETC___d867) && !((((INST_top.DEF_CAN_FIRE_RL_action_l188c13 || INST_top.DEF_CAN_FIRE_RL_action_l182c13) || (INST_top.DEF_CAN_FIRE_RL_action_l181c13 || INST_top.DEF_CAN_FIRE_RL_action_l180c19)) || ((INST_top.DEF_CAN_FIRE_RL_action_l179c19 || INST_top.DEF_CAN_FIRE_RL_action_l178c19) || (INST_top.DEF_CAN_FIRE_RL_action_l172c13 || INST_top.DEF_CAN_FIRE_RL_action_l171c13))) || (INST_top.DEF_CAN_FIRE_RL_action_l170c19 || INST_top.DEF_CAN_FIRE_RL_action_l169c19));
	 INST_top.DEF_WILL_FIRE_RL_action_l167c19 = INST_top.DEF_CAN_FIRE_RL_action_l167c19;
	 DEF_INST_top_DEF_NOT_start_wire_whas__39_40_OR_NOT_start_wire_w_ETC___d843 = !DEF_INST_top_DEF_start_wire_whas____d839 || !DEF_INST_top_DEF_start_wire_wget____d841;
	 INST_top.DEF_CAN_FIRE_RL_idle_l165c22 = (DEF_INST_top_DEF_NOT_start_wire_whas__39_40_OR_NOT_start_wire_w_ETC___d843 && (DEF_INST_top_DEF_NOT_abort_whas__36_58_OR_NOT_abort_wget__37_59___d860 && DEF_INST_top_DEF_state_mkFSMstate_read__63_EQ_11___d866)) && !((((INST_top.DEF_CAN_FIRE_RL_action_l188c13 || INST_top.DEF_CAN_FIRE_RL_action_l182c13) || (INST_top.DEF_CAN_FIRE_RL_action_l181c13 || INST_top.DEF_CAN_FIRE_RL_action_l180c19)) || ((INST_top.DEF_CAN_FIRE_RL_action_l179c19 || INST_top.DEF_CAN_FIRE_RL_action_l178c19) || (INST_top.DEF_CAN_FIRE_RL_action_l172c13 || INST_top.DEF_CAN_FIRE_RL_action_l171c13))) || (INST_top.DEF_CAN_FIRE_RL_action_l170c19 || INST_top.DEF_CAN_FIRE_RL_action_l169c19));
	 INST_top.DEF_WILL_FIRE_RL_idle_l165c22 = INST_top.DEF_CAN_FIRE_RL_idle_l165c22;
	 INST_top.DEF_CAN_FIRE_RL_state_handle_abort = (DEF_INST_top_DEF_abort_whas__36_AND_abort_wget__37___d838 && DEF_INST_top_DEF_NOT_start_wire_whas__39_40_OR_NOT_start_wire_w_ETC___d843) && !((((INST_top.DEF_CAN_FIRE_RL_action_l188c13 || INST_top.DEF_CAN_FIRE_RL_action_l182c13) || (INST_top.DEF_CAN_FIRE_RL_action_l181c13 || INST_top.DEF_CAN_FIRE_RL_action_l180c19)) || ((INST_top.DEF_CAN_FIRE_RL_action_l179c19 || INST_top.DEF_CAN_FIRE_RL_action_l178c19) || (INST_top.DEF_CAN_FIRE_RL_action_l172c13 || INST_top.DEF_CAN_FIRE_RL_action_l171c13))) || ((INST_top.DEF_CAN_FIRE_RL_action_l170c19 || INST_top.DEF_CAN_FIRE_RL_action_l169c19) || INST_top.DEF_CAN_FIRE_RL_restart));
	 INST_top.DEF_WILL_FIRE_RL_state_handle_abort = INST_top.DEF_CAN_FIRE_RL_state_handle_abort;
	 if (INST_top.DEF_WILL_FIRE_RL_action_l167c19)
	   INST_top.RL_action_l167c19();
	 if (INST_top.DEF_WILL_FIRE_RL_idle_l165c22)
	   INST_top.RL_idle_l165c22();
	 if (INST_top.DEF_WILL_FIRE_RL_state_every)
	   INST_top.RL_state_every();
	 if (INST_top.DEF_WILL_FIRE_RL_state_fired__dreg_update)
	   INST_top.RL_state_fired__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_state_handle_abort)
	   INST_top.RL_state_handle_abort();
	 if (INST_top.DEF_WILL_FIRE___me_check_13)
	   INST_top.__me_check_13();
	 if (INST_top.DEF_WILL_FIRE___me_check_14)
	   INST_top.__me_check_14();
	 if (INST_top.DEF_WILL_FIRE___me_check_15)
	   INST_top.__me_check_15();
	 if (INST_top.DEF_WILL_FIRE___me_check_16)
	   INST_top.__me_check_16();
	 if (INST_top.DEF_WILL_FIRE___me_check_17)
	   INST_top.__me_check_17();
	 if (INST_top.DEF_WILL_FIRE___me_check_18)
	   INST_top.__me_check_18();
	 if (INST_top.DEF_WILL_FIRE___me_check_19)
	   INST_top.__me_check_19();
	 if (INST_top.DEF_WILL_FIRE___me_check_20)
	   INST_top.__me_check_20();
	 if (INST_top.DEF_WILL_FIRE___me_check_21)
	   INST_top.__me_check_21();
	 if (INST_top.DEF_WILL_FIRE___me_check_22)
	   INST_top.__me_check_22();
	 if (INST_top.DEF_WILL_FIRE_RL_start_reg__dreg_update)
	   INST_top.RL_start_reg__dreg_update();
	 INST_top.INST_state_fired_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_overlap_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_state_set_pw.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_abort.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_reg_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_start_wire.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_3_write_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_3_read_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_3_data_out_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_3_data_in_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_3_address_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_3_control_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_2_write_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_2_read_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_2_data_out_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_2_data_in_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_2_address_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_2_control_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_1_write_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_1_read_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_1_data_out_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_1_data_in_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_1_address_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_1_control_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_0_write_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_0_read_req_signal.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_0_data_out_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_0_data_in_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_0_address_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_csr_s_0_control_written.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_63.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_62.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_61.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_60.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_59.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_58.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_57.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_56.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_55.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_54.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_53.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_52.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_51.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_50.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_49.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_48.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_47.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_46.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_45.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_44.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_43.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_42.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_41.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_40.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_39.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_38.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_37.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_36.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_35.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_34.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_33.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_32.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_31.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_30.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_29.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_28.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_27.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_26.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_25.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_24.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_23.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_22.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_21.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_20.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_19.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_18.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_17.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_16.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_15.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_14.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_13.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_12.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_11.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_10.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_9.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_8.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_7.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_6.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_5.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_4.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_my_ram_inst_data.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_my_ram_inst_data.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_1.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_2.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_3.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_4.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_5.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_6.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_7.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_8.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_9.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_10.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_11.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_12.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_13.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_14.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_15.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_16.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_17.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_18.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_19.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_20.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_21.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_22.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_23.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_24.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_25.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_26.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_27.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_28.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_29.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_30.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_31.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_32.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_33.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_34.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_35.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_36.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_37.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_38.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_39.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_40.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_41.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_42.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_43.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_44.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_45.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_46.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_47.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_48.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_49.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_50.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_51.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_52.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_53.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_54.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_55.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_56.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_57.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_58.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_59.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_60.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_61.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_62.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_data_63.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_0_control_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_0_address_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_0_data_in_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_0_data_out_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_1_control_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_1_address_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_1_data_in_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_1_data_out_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_2_control_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_2_address_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_2_data_in_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_2_data_out_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_3_control_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_3_address_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_3_data_in_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_csr_s_3_data_out_inner_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_my_ram_inst_dummy.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_start_reg_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_mkFSMstate.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_fired.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_state_can_overlap.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_running.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTestDRAM::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTestDRAM_instance = new MOD_mkTestDRAM(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTestDRAM_instance->INST_my_ram_inst_data.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_1.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_2.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_3.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_4.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_5.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_6.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_7.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_8.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_9.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_10.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_11.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_12.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_13.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_14.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_15.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_16.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_17.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_18.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_19.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_20.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_21.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_22.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_23.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_24.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_25.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_26.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_27.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_28.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_29.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_30.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_31.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_32.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_33.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_34.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_35.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_36.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_37.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_38.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_39.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_40.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_41.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_42.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_43.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_44.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_45.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_46.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_47.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_48.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_49.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_50.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_51.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_52.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_53.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_54.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_55.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_56.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_57.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_58.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_59.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_60.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_61.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_62.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_data_63.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_0_control_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_0_address_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_0_data_in_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_0_data_out_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_0_read_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_0_write_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_1_control_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_1_address_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_1_data_in_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_1_data_out_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_1_read_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_1_write_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_2_control_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_2_address_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_2_data_in_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_2_data_out_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_2_read_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_2_write_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_3_control_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_3_address_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_3_data_in_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_3_data_out_written.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_3_read_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_my_ram_inst_csr_s_3_write_req_signal.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_start_wire.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_start_reg_2.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_abort.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_state_set_pw.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_state_overlap_pw.set_clk_0)("CLK");
  (mkTestDRAM_instance->INST_state_fired_1.set_clk_0)("CLK");
  (mkTestDRAM_instance->set_clk_0)("CLK");
}
void MODEL_mkTestDRAM::destroy_model()
{
  delete mkTestDRAM_instance;
  mkTestDRAM_instance = NULL;
}
void MODEL_mkTestDRAM::reset_model(bool asserted)
{
  (mkTestDRAM_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTestDRAM::get_instance()
{
  return mkTestDRAM_instance;
}

/* Fill in version numbers */
void MODEL_mkTestDRAM::get_version(unsigned int *year,
				   unsigned int *month,
				   char const **annotation,
				   char const **build)
{
  *year = 0u;
  *month = 0u;
  *annotation = NULL;
  *build = "2c1ed34";
}

/* Get the model creation time */
time_t MODEL_mkTestDRAM::get_creation_time()
{
  
  /* Mon Dec 14 12:32:57 UTC 2020 */
  return 1607949177llu;
}

/* State dumping function */
void MODEL_mkTestDRAM::dump_state()
{
  (mkTestDRAM_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTestDRAM & mkTestDRAM_backing(tSimStateHdl simHdl)
{
  static MOD_mkTestDRAM *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTestDRAM(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTestDRAM::dump_VCD_defs()
{
  (mkTestDRAM_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTestDRAM::dump_VCD(tVCDDumpType dt)
{
  (mkTestDRAM_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTestDRAM_backing(sim_hdl));
}
